import java.util.ArrayList;
import java.util.List;

public class MainClass {
    public static void main(String[] args) {
        String[] inputLines = ("acc -17\n" +
                "nop +318\n" +
                "jmp +1\n" +
                "acc -10\n" +
                "jmp +394\n" +
                "acc +43\n" +
                "acc +47\n" +
                "nop +570\n" +
                "jmp +176\n" +
                "acc -9\n" +
                "jmp +322\n" +
                "jmp +73\n" +
                "acc +4\n" +
                "acc -4\n" +
                "jmp +460\n" +
                "jmp +228\n" +
                "acc +25\n" +
                "acc +39\n" +
                "jmp +50\n" +
                "acc -12\n" +
                "acc -14\n" +
                "nop +275\n" +
                "jmp +489\n" +
                "acc -11\n" +
                "jmp +338\n" +
                "acc +21\n" +
                "acc +10\n" +
                "jmp +1\n" +
                "acc +20\n" +
                "jmp +445\n" +
                "acc +7\n" +
                "jmp +419\n" +
                "acc -8\n" +
                "acc +32\n" +
                "jmp +181\n" +
                "acc +19\n" +
                "acc +5\n" +
                "acc +46\n" +
                "jmp +417\n" +
                "acc +28\n" +
                "acc +23\n" +
                "acc +16\n" +
                "jmp +225\n" +
                "jmp +317\n" +
                "jmp +309\n" +
                "jmp +69\n" +
                "acc -6\n" +
                "acc -6\n" +
                "jmp +127\n" +
                "acc +49\n" +
                "nop -38\n" +
                "jmp +467\n" +
                "acc +0\n" +
                "acc -12\n" +
                "acc -14\n" +
                "jmp -46\n" +
                "acc +14\n" +
                "acc +2\n" +
                "acc +2\n" +
                "jmp +311\n" +
                "acc +33\n" +
                "jmp +364\n" +
                "nop +234\n" +
                "acc +24\n" +
                "acc +37\n" +
                "acc +18\n" +
                "jmp +22\n" +
                "jmp +303\n" +
                "jmp +414\n" +
                "jmp +318\n" +
                "acc +22\n" +
                "acc +27\n" +
                "jmp +1\n" +
                "jmp +150\n" +
                "acc +34\n" +
                "acc +15\n" +
                "nop +200\n" +
                "acc +6\n" +
                "jmp +320\n" +
                "nop +534\n" +
                "acc +29\n" +
                "jmp +147\n" +
                "nop -20\n" +
                "jmp +255\n" +
                "jmp +10\n" +
                "acc -15\n" +
                "acc +3\n" +
                "jmp +338\n" +
                "nop +362\n" +
                "acc -4\n" +
                "jmp +1\n" +
                "jmp +286\n" +
                "acc -1\n" +
                "jmp +497\n" +
                "acc -4\n" +
                "acc +23\n" +
                "acc +4\n" +
                "jmp +400\n" +
                "acc +35\n" +
                "acc +50\n" +
                "jmp +133\n" +
                "acc -17\n" +
                "jmp -90\n" +
                "jmp +7\n" +
                "acc -17\n" +
                "jmp +472\n" +
                "acc +20\n" +
                "jmp +280\n" +
                "jmp +133\n" +
                "jmp -15\n" +
                "jmp +16\n" +
                "acc -19\n" +
                "acc -2\n" +
                "jmp -64\n" +
                "acc -17\n" +
                "jmp +1\n" +
                "jmp +385\n" +
                "acc -5\n" +
                "acc +34\n" +
                "jmp +382\n" +
                "acc +24\n" +
                "acc -17\n" +
                "acc +0\n" +
                "acc +15\n" +
                "jmp +466\n" +
                "jmp +300\n" +
                "acc +16\n" +
                "jmp +302\n" +
                "nop +479\n" +
                "acc +16\n" +
                "jmp +71\n" +
                "acc +23\n" +
                "jmp +1\n" +
                "acc +8\n" +
                "jmp +154\n" +
                "jmp +410\n" +
                "acc -8\n" +
                "jmp +402\n" +
                "acc +48\n" +
                "acc +42\n" +
                "acc +22\n" +
                "acc +35\n" +
                "jmp +50\n" +
                "jmp -7\n" +
                "acc -13\n" +
                "acc +37\n" +
                "acc +24\n" +
                "jmp +243\n" +
                "jmp +410\n" +
                "acc -3\n" +
                "acc +45\n" +
                "jmp +416\n" +
                "acc +2\n" +
                "acc +25\n" +
                "jmp -109\n" +
                "jmp -41\n" +
                "jmp +318\n" +
                "acc -8\n" +
                "acc -12\n" +
                "jmp +169\n" +
                "nop +393\n" +
                "acc +7\n" +
                "acc -12\n" +
                "acc +35\n" +
                "jmp +381\n" +
                "acc +41\n" +
                "nop -98\n" +
                "acc +15\n" +
                "acc -19\n" +
                "jmp +218\n" +
                "acc +24\n" +
                "acc +47\n" +
                "jmp +65\n" +
                "acc +29\n" +
                "jmp -129\n" +
                "acc +23\n" +
                "acc -13\n" +
                "nop +60\n" +
                "jmp -26\n" +
                "nop -4\n" +
                "acc -5\n" +
                "acc +13\n" +
                "nop -12\n" +
                "jmp -13\n" +
                "jmp -53\n" +
                "acc +21\n" +
                "jmp +276\n" +
                "nop -27\n" +
                "jmp +165\n" +
                "acc +42\n" +
                "nop +43\n" +
                "jmp +1\n" +
                "acc +26\n" +
                "acc +22\n" +
                "acc -3\n" +
                "jmp +405\n" +
                "acc +29\n" +
                "nop -118\n" +
                "acc +21\n" +
                "nop -190\n" +
                "jmp +217\n" +
                "acc -1\n" +
                "nop +223\n" +
                "acc -8\n" +
                "acc +45\n" +
                "jmp +49\n" +
                "acc +8\n" +
                "acc +22\n" +
                "jmp +209\n" +
                "acc +44\n" +
                "jmp +66\n" +
                "acc +7\n" +
                "acc -7\n" +
                "acc +48\n" +
                "jmp +318\n" +
                "nop +398\n" +
                "acc +2\n" +
                "jmp +16\n" +
                "nop +207\n" +
                "nop +358\n" +
                "acc +45\n" +
                "acc +48\n" +
                "jmp +267\n" +
                "nop +248\n" +
                "acc +26\n" +
                "jmp +307\n" +
                "acc +27\n" +
                "jmp -197\n" +
                "jmp -68\n" +
                "acc +34\n" +
                "acc +25\n" +
                "acc -13\n" +
                "jmp +133\n" +
                "jmp -77\n" +
                "acc -13\n" +
                "acc +10\n" +
                "jmp -193\n" +
                "jmp -62\n" +
                "acc +4\n" +
                "acc -14\n" +
                "jmp +261\n" +
                "jmp +151\n" +
                "jmp +208\n" +
                "acc -10\n" +
                "jmp +40\n" +
                "acc +31\n" +
                "jmp -216\n" +
                "acc +23\n" +
                "acc +34\n" +
                "jmp +364\n" +
                "nop +205\n" +
                "acc -3\n" +
                "acc +14\n" +
                "jmp +59\n" +
                "nop +359\n" +
                "acc -4\n" +
                "jmp +1\n" +
                "jmp -248\n" +
                "acc +47\n" +
                "acc +35\n" +
                "jmp +184\n" +
                "acc +16\n" +
                "nop -92\n" +
                "acc -12\n" +
                "jmp +354\n" +
                "acc +27\n" +
                "jmp -152\n" +
                "acc -14\n" +
                "acc -16\n" +
                "acc +43\n" +
                "jmp +147\n" +
                "acc +45\n" +
                "acc +24\n" +
                "acc +6\n" +
                "nop -46\n" +
                "jmp +21\n" +
                "acc +26\n" +
                "jmp +1\n" +
                "jmp +293\n" +
                "acc -8\n" +
                "acc +12\n" +
                "acc -19\n" +
                "acc -9\n" +
                "jmp +94\n" +
                "jmp +299\n" +
                "acc +10\n" +
                "acc -2\n" +
                "jmp +75\n" +
                "acc -7\n" +
                "acc +3\n" +
                "acc +47\n" +
                "jmp +171\n" +
                "acc +16\n" +
                "acc +44\n" +
                "acc -3\n" +
                "jmp +14\n" +
                "acc +30\n" +
                "acc +34\n" +
                "jmp -178\n" +
                "acc +35\n" +
                "nop -238\n" +
                "acc +39\n" +
                "jmp +1\n" +
                "jmp -133\n" +
                "acc +34\n" +
                "acc -6\n" +
                "jmp -276\n" +
                "acc +1\n" +
                "jmp -207\n" +
                "acc +10\n" +
                "jmp -43\n" +
                "jmp -302\n" +
                "acc -1\n" +
                "nop -29\n" +
                "jmp +1\n" +
                "acc +17\n" +
                "jmp -281\n" +
                "acc +17\n" +
                "jmp -109\n" +
                "jmp +1\n" +
                "acc +13\n" +
                "nop -9\n" +
                "jmp +245\n" +
                "acc +5\n" +
                "nop -15\n" +
                "acc +3\n" +
                "acc +7\n" +
                "jmp +65\n" +
                "acc -11\n" +
                "jmp -313\n" +
                "acc +47\n" +
                "jmp +29\n" +
                "jmp -289\n" +
                "acc +18\n" +
                "acc -17\n" +
                "nop +73\n" +
                "acc -12\n" +
                "jmp +80\n" +
                "acc +32\n" +
                "acc -4\n" +
                "acc +3\n" +
                "jmp -126\n" +
                "acc +16\n" +
                "jmp -275\n" +
                "nop -188\n" +
                "acc -3\n" +
                "acc +14\n" +
                "jmp -155\n" +
                "acc +33\n" +
                "acc -19\n" +
                "nop -166\n" +
                "acc +20\n" +
                "jmp +30\n" +
                "nop -169\n" +
                "acc +49\n" +
                "nop +168\n" +
                "jmp -24\n" +
                "nop -345\n" +
                "acc +34\n" +
                "jmp -40\n" +
                "jmp -56\n" +
                "jmp +29\n" +
                "jmp +191\n" +
                "acc +24\n" +
                "jmp +219\n" +
                "acc +34\n" +
                "acc +27\n" +
                "acc +11\n" +
                "jmp -260\n" +
                "jmp -339\n" +
                "acc +15\n" +
                "nop +16\n" +
                "jmp +1\n" +
                "jmp +138\n" +
                "jmp +1\n" +
                "jmp +1\n" +
                "jmp +14\n" +
                "acc -11\n" +
                "acc +45\n" +
                "jmp -19\n" +
                "acc +0\n" +
                "jmp +27\n" +
                "acc +0\n" +
                "nop +128\n" +
                "jmp -65\n" +
                "nop -23\n" +
                "jmp -318\n" +
                "jmp -325\n" +
                "jmp +1\n" +
                "jmp -229\n" +
                "jmp -270\n" +
                "jmp -137\n" +
                "acc +34\n" +
                "acc +7\n" +
                "jmp +1\n" +
                "jmp -346\n" +
                "acc +18\n" +
                "jmp +37\n" +
                "acc +40\n" +
                "acc -16\n" +
                "nop -146\n" +
                "acc +35\n" +
                "jmp -12\n" +
                "acc +1\n" +
                "acc +27\n" +
                "acc +44\n" +
                "acc +8\n" +
                "jmp -276\n" +
                "acc +16\n" +
                "acc +42\n" +
                "nop -342\n" +
                "acc +13\n" +
                "jmp -165\n" +
                "acc -11\n" +
                "acc -17\n" +
                "acc -10\n" +
                "jmp -26\n" +
                "acc +10\n" +
                "acc +43\n" +
                "jmp -276\n" +
                "acc +5\n" +
                "acc +34\n" +
                "acc +17\n" +
                "acc -9\n" +
                "jmp +99\n" +
                "acc +29\n" +
                "jmp -370\n" +
                "acc -11\n" +
                "jmp -412\n" +
                "acc +47\n" +
                "acc +21\n" +
                "acc -12\n" +
                "jmp -136\n" +
                "jmp -124\n" +
                "acc +12\n" +
                "acc +0\n" +
                "acc +25\n" +
                "acc +27\n" +
                "jmp -290\n" +
                "acc +5\n" +
                "acc +49\n" +
                "acc +32\n" +
                "nop +29\n" +
                "jmp -202\n" +
                "nop -296\n" +
                "acc -12\n" +
                "acc +9\n" +
                "acc +21\n" +
                "jmp +23\n" +
                "jmp -345\n" +
                "acc +26\n" +
                "nop -123\n" +
                "jmp -373\n" +
                "nop +118\n" +
                "jmp +43\n" +
                "acc -15\n" +
                "jmp -386\n" +
                "jmp +1\n" +
                "nop -370\n" +
                "acc +47\n" +
                "nop -141\n" +
                "jmp -426\n" +
                "acc +42\n" +
                "acc +12\n" +
                "acc +4\n" +
                "nop -103\n" +
                "jmp -122\n" +
                "acc +23\n" +
                "acc -4\n" +
                "acc +11\n" +
                "jmp -314\n" +
                "jmp -73\n" +
                "nop -1\n" +
                "jmp -411\n" +
                "acc +13\n" +
                "acc +9\n" +
                "nop -372\n" +
                "jmp -293\n" +
                "acc +46\n" +
                "acc +3\n" +
                "acc -1\n" +
                "jmp +86\n" +
                "acc +36\n" +
                "jmp +100\n" +
                "acc +27\n" +
                "acc +49\n" +
                "nop -4\n" +
                "acc +47\n" +
                "jmp -445\n" +
                "acc +31\n" +
                "acc +47\n" +
                "acc -11\n" +
                "acc +14\n" +
                "jmp -181\n" +
                "nop -438\n" +
                "acc +31\n" +
                "jmp -428\n" +
                "nop -115\n" +
                "nop -244\n" +
                "jmp -464\n" +
                "jmp -29\n" +
                "nop -240\n" +
                "jmp -241\n" +
                "acc -12\n" +
                "jmp -329\n" +
                "nop +78\n" +
                "acc +6\n" +
                "jmp +1\n" +
                "acc +49\n" +
                "jmp -322\n" +
                "jmp -133\n" +
                "acc +20\n" +
                "nop -83\n" +
                "acc +35\n" +
                "acc +29\n" +
                "jmp -41\n" +
                "acc +15\n" +
                "jmp -46\n" +
                "jmp -29\n" +
                "acc +45\n" +
                "acc -14\n" +
                "acc +21\n" +
                "jmp -366\n" +
                "nop +84\n" +
                "acc -6\n" +
                "acc +25\n" +
                "acc -17\n" +
                "jmp -326\n" +
                "acc -5\n" +
                "nop -159\n" +
                "acc +5\n" +
                "jmp -171\n" +
                "acc +42\n" +
                "jmp -28\n" +
                "acc +42\n" +
                "acc -11\n" +
                "acc +45\n" +
                "acc +19\n" +
                "jmp -305\n" +
                "acc +38\n" +
                "acc -13\n" +
                "acc -16\n" +
                "jmp -134\n" +
                "acc +45\n" +
                "jmp -256\n" +
                "acc -15\n" +
                "acc -18\n" +
                "acc +28\n" +
                "jmp -114\n" +
                "acc -11\n" +
                "acc +47\n" +
                "nop -420\n" +
                "jmp -90\n" +
                "nop -330\n" +
                "jmp +13\n" +
                "acc -15\n" +
                "acc +9\n" +
                "jmp -159\n" +
                "acc -12\n" +
                "acc +0\n" +
                "acc +0\n" +
                "jmp -538\n" +
                "acc +31\n" +
                "acc +24\n" +
                "acc +32\n" +
                "acc -16\n" +
                "jmp -95\n" +
                "jmp -466\n" +
                "acc +19\n" +
                "acc +2\n" +
                "jmp -172\n" +
                "acc -12\n" +
                "jmp -207\n" +
                "acc +39\n" +
                "acc +18\n" +
                "acc +5\n" +
                "jmp -211\n" +
                "nop -507\n" +
                "jmp +1\n" +
                "jmp -197\n" +
                "nop -227\n" +
                "acc +28\n" +
                "jmp -494\n" +
                "acc +22\n" +
                "acc +2\n" +
                "acc -14\n" +
                "jmp -377\n" +
                "acc +8\n" +
                "acc +29\n" +
                "jmp -573\n" +
                "acc -17\n" +
                "acc +14\n" +
                "acc +29\n" +
                "acc +11\n" +
                "jmp -351\n" +
                "acc +9\n" +
                "nop -540\n" +
                "acc +30\n" +
                "nop -344\n" +
                "jmp -564\n" +
                "acc -4\n" +
                "nop -465\n" +
                "jmp -293\n" +
                "acc -18\n" +
                "acc +5\n" +
                "acc +29\n" +
                "jmp -302\n" +
                "acc -17\n" +
                "acc +14\n" +
                "acc +2\n" +
                "acc -11\n" +
                "jmp -527\n" +
                "jmp -563\n" +
                "acc +14\n" +
                "acc +10\n" +
                "jmp -505\n" +
                "acc +43\n" +
                "jmp -188\n" +
                "nop -448\n" +
                "acc +44\n" +
                "acc +3\n" +
                "acc +16\n" +
                "jmp +1\n").split("\n");

        int accumulator = 0;
        List<String>instructionsHistory = new ArrayList<>();

        for (int i = 0; i < inputLines.length;) {
            boolean instructionAlreadyExecuted = false;

            for (int z = 0; z < instructionsHistory.size(); z++) {
                if(inputLines[i].equals(instructionsHistory.get(z).substring(0,instructionsHistory.get(z).indexOf("_")))) {
                    if (i == Integer.parseInt(instructionsHistory.get(z).substring(instructionsHistory.get(z).indexOf("_")+1)))
                        instructionAlreadyExecuted = true;
                }
            }

            if(instructionAlreadyExecuted)
                break;

            String operation = inputLines[i].substring(0,inputLines[i].indexOf(" "));
            String argumentSign = inputLines[i].substring(inputLines[i].indexOf(" ")+1,inputLines[i].indexOf(" ")+2);
            String argument = inputLines[i].substring(inputLines[i].indexOf(" ")+2);

            switch (operation)
            {
                case "acc":
                    if(argumentSign.equals("-"))
                        accumulator -= Integer.parseInt(argument);
                    else
                        accumulator += Integer.parseInt(argument);
                    instructionsHistory.add(operation+" "+argumentSign+argument+"_"+i);
                    break;
                case "jmp":
                    if(argumentSign.equals("-"))
                        i -= Integer.parseInt(argument);
                    else
                        i+= Integer.parseInt(argument);
                    instructionsHistory.add(operation+" "+argumentSign+argument+"_"+i);
                    continue;
                case "nop":
                    instructionsHistory.add(operation+" "+argumentSign+argument+"_"+i);
                    break;
            }
            i++;
        }

        System.out.println(accumulator);
    }
}
